create database Bank;

select * from bank_loan

-- Count Total Loan Application
select COUNT(id) as Total_Loan_Application
from bank_loan;

-- Month-to-Date(MTD) of Issue Date Loan
SELECT COUNT(ID) AS MTD_TOTAL_LOAN_APPLICATION 
FROM bank_loan
WHERE 
MONTH(issue_date) = 12 AND YEAR(ISSUE_DATE) = 2021

--  Previous Month-to-Date 
SELECT COUNT(ID) AS P_MTD_TOTAL_LOAN_APPLICATION 
FROM bank_loan
WHERE 
MONTH(issue_date) = 11 AND YEAR(ISSUE_DATE) = 2021

-- Total Funded Amount

SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED
FROM bank_loan;

--MTD TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 12 AND YEAR(ISSUE_DATE) = 2021;

-- PREVOUS_MTD TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS P_MTD_TOTAL_FUNDED 
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 11 AND YEAR(ISSUE_DATE) = 2021;

--TOTAL AMOUNT RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED 
FROM bank_loan

-- MTD TOTAL AMOUNT RECEIVED 
SELECT SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED 
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 12 AND YEAR(ISSUE_DATE) = 2021

--PREVIOUS MTD AMOUNT RECEIVED 
SELECT SUM(TOTAL_PAYMENT) AS P_MTD_AMOUNT_RECEIVED
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 11 AND YEAR(ISSUE_DATE) = 2021

-- AVG INTEREST RATE 
SELECT AVG(INT_RATE)*100 AS AVG_INT_RATE
FROM bank_loan

-- AVG INTEREST RATE ROUND
SELECT ROUND(AVG(INT_RATE),2) * 100 AS AVG_INT_RATE
FROM bank_loan

SELECT ROUND(AVG(INT_RATE),4) * 100 AS AVG_INT_RATE
FROM bank_loan

-- MTD AVG INTREST RATE
SELECT ROUND(AVG(INT_RATE),4) * 100 AS MTD_AVG_INTEREST_RATE
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 12 AND YEAR(issue_date) = 2021

--PREVIOUS MTD AVG INTEREST RATE
SELECT ROUND(AVG(INT_RATE),4) * 100 AS P_MTD_AVG_INTEREST_RATE
FROM bank_loan
WHERE
MONTH(ISSUE_DATE) = 11 AND YEAR(ISSUE_DATE) = 2021

select loan_status 
from 
bank_loan;

--GOOD LOAN AND BAD LOAN
SELECT 
     (COUNT(CASE WHEN LOAN_STATUS = 'FULLY PAID' OR LOAN_STATUS = 'CURRENT'
	        THEN 
			ID END)*100)
     /
	 COUNT(ID) AS GOOD_LOAN_PERCENTAGE 
FROM bank_loan;

-- GOOD LOAN APPLICATION 
SELECT COUNT(ID) AS GOOD_LOAN_APPLICATION 
FROM bank_loan
WHERE 
loan_status = 'FULLY PAID' OR loan_status = 'CURRENT';

--GOOD LOAN FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS GOOD_LOAN_FUNDED_AMOUNT 
FROM BANK_LOAN
WHERE 
LOAN_STATUS ='FULLY PAID' OR LOAN_STATUS ='CURRENT';

--GOOD LOAN TOTAL RECEIVED AMOUNT
SELECT SUM(TOTAL_PAYMENT) AS GOOD_LOAN_TOTAL_AMOUNT_RECEIVED 
FROM BANK_LOAN
WHERE 
LOAN_STATUS = 'FULLY PAID' OR LOAN_STATUS = 'CURRENT';

-- BAD LOAN 
SELECT 
     (COUNT(CASE WHEN LOAN_STATUS = 'CHARGED OFF' THEN ID END) *100)
	 /
	 COUNT(ID) AS BAD_LOAN
FROM bank_loan;

--BAD LOAN APPLICATION 
SELECT COUNT(ID) AS BADLOANAPPLICATION
FROM bank_loan
WHERE
loan_status = 'CHARGED OFF';

-- BAD LOAN FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS BADLOANFUNDEDAMOUNT
FROM bank_loan
WHERE 
loan_status = 'CHARGED OFF';

--BAD LOAN RECEIVED AMOUNT 
SELECT SUM(TOTAL_PAYMENT) AS BADLOANRECEIVEDAMOUNT
FROM bank_loan
WHERE
loan_status = 'CHARGED OFF';

-- LOAN STATUS 
SELECT 
     LOAN_STATUS,
	 COUNT(ID) AS LOAN_COUNT,
	 SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED, 
	 SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	 AVG(INT_RATE * 100) AS AVG_INTEREST_RATE,
	 AVG(DTI * 100) AS AVG_DTI
FROM bank_loan
GROUP BY 
loan_status;

-- LOAN STATUS MTD
SELECT 
      LOAN_STATUS,  
      SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED ,
	  SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT
FROM bank_loan
WHERE 
MONTH(ISSUE_DATE) = 12
GROUP BY 
loan_status;

--METRIC 
SELECT 
      MONTH(ISSUE_DATE) AS MONTH_NUMBER,
	  DATENAME(MONTH,ISSUE_DATE) AS MONTH_NAME,
	  COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  MONTH(ISSUE_DATE) , DATENAME(MONTH,ISSUE_DATE) 
ORDER BY  MONTH(ISSUE_DATE) ;

-- ADDRESS
SELECT
      ADDRESS_STATE,
      COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  ADDRESS_STATE 
ORDER BY  ADDRESS_STATE ;

--TERM
SELECT
      TERM,
      COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  term 
ORDER BY  term DESC ;

--EMPLOYEE LENGTH
SELECT
      emp_length,
      COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  emp_length
ORDER BY  emp_length DESC ;

--PURPOSE
SELECT
      purpose AS PURPOSE,
      COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  PURPOSE 
ORDER BY  PURPOSE DESC ;

--HOME OWNERSHIP
SELECT
      home_ownership AS HOME_OWNERSHIP,
      COUNT(ID) AS TOTAL_APPLICATION,
	  SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	  SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM bank_loan
GROUP BY  HOME_OWNERSHIP 
ORDER BY  HOME_OWNERSHIP DESC ;